repos:
    - repo: git@github.com:astral-sh/ruff-pre-commit.git
      rev: v0.4.4
      hooks:
          - id: ruff
          - id: ruff-format

    - repo: git@github.com:pre-commit/mirrors-mypy.git
      rev: v1.9.0
      hooks:
          - id: mypy
